name = "ManifoldMeasures"
uuid = "220fa119-603f-4115-915b-ee7b5d8454ef"
authors = ["Seth Axen <seth.axen@gmail.com> and contributors"]
version = "0.1.0"

Manifolds = "1cead3c2-87b3-11e9-0ccd-23c62b72b94e"
MeasureTheory = "eadaa1a4-d27c-401d-8699-e962e1bbc33b"
[compat]
Manifolds = "0.5"
MeasureTheory = "0.9.3"
julia = "1.3"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
